# docker-compose.yaml

version: '2' # version of docker-compose to use

services: #container configurations
  db: 
    image: mysql:5.7 
    volumes: 
      - ./data:/docker-entrypoint-initdb.d 
    restart: always 
    environment: # environment varialbes. User can replace 'user-to-set'
      MYSQL_ROOT_PASSWORD: user-to-set
      MYSQL_DATABASE: user-to-set
      MYSQL_USER: user-to-set
      MYSQL_PASSWORD: user-to-set
    networks:
      -back

  wordpress: 
    depends_on: 
      - db
    image: wordpress:latest #if you want a specific image, you can replace with wordpress:4.9.5-php5.6
    ports:
      - "8000:80" 
    restart: always
    environment: # can be replaced with env_file
      WORDPRESS_DB_HOST: db:3306 
      WORDPRESS_DB_PASSWORD: user-to-set 
    volumes: # persistance - tell Docker to keep these in tact. To replace with the entire wp-content directory
      - ./wp/wp-content:/var/www/html/wp-content
      - ./wp/wp-config.php:/var/www/html/wp-config.php
    networks:
      - back

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8181:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: user-to-set #this must match you entered under 'db'
    networks:
      - back

networks:
  back: