version: '3.6'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    links:
      - wordpress
    depends_on:
      - wordpress
    ports:
      - "8080:80"
      # - "443:443"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
      - ./wp:/var/www/html/:ro

  wordpress:
    build:
      context: .
      dockerfile: wordpress-fpm/Dockerfile
    depends_on:
      - mysql
    restart: always
    volumes:
      - ./wp:/var/www/html/
      - ./wordpress-fpm/info.php:/var/www/html/info.php # Do not let this get committed to your repository
      # To use the latest Wordpress version, only mount the content
      # - ./wp/wp-content:/var/www/html/wp-content
      # - ./wp/wp-config.php:/var/www/html/wp-config.php

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wp
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
    ports:
      - "3306:3306"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql

  # redis:
  #   image: redis:alpine
  #   restart: always
  #   ports:
  #     - '6379:6379'

  # phpmyadmin:
  #   depends_on:
  #     - mysql
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   ports:
  #     - 8181:80
  #   environment:
  #     PMA_HOST: mysql
  #     MYSQL_ROOT_PASSWORD: wp #this must match you entered under 'mysql'
  #   networks:
  #     - back

volumes:
  db:

# networks:
#   back:

