version: '2'

services: #container configurations
  db: 
    image: mysql:5.7 
    volumes: 
      - ./data:/docker-entrypoint-initdb.d 
    restart: always 
    environment: # environment varialbes. User can replace 'example'
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
    networks:
      -back

  wordpress: 
    depends_on: 
      - db
    image: wordpress:latest 
    ports:
      - "8000:80" 
    restart: always
    environment: # can be replaced with env_file
      WORDPRESS_DB_HOST: db:3306 
      WORDPRESS_DB_PASSWORD: example 
    volumes: # persistance - tell Docker to keep these in tact. To replace with the entire wp-content directory
      - ./wp-content/themes/<theme-name>:/var/www/html/wp-content/themes/<theme-name> 
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
    networks:
      - back

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8181:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: example #replace if not using 'example' in db section
    networks:
      - back

networks:
  back: