version: '3.6'

services:

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    links:
      - wordpress
    depends_on:
      - wordpress
    ports:
      - "8080:80"
      # - "443:443"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
      - $WP:/var/www/html/:ro

  wordpress:
    build:
      context: .
      dockerfile: wordpress-fpm/Dockerfile
    depends_on:
      - mysql
    restart: always
    volumes:
      - $WP/:/var/www/html/
      - ./info.php:/var/www/html/info.php
      - ./bin/config.sh:/var/www/html/bin/config.sh
      # To use the latest Wordpress version, only mount the content
      # - $WP/wp-content:/var/www/html/wp-content
      # - $WP/wp-config.php:/var/www/html/wp-config.php

  # wordpress:
  #   depends_on:
  #     - db
  #   image: wordpress:latest #if you want a specific image, you can replace with wordpress:4.9.5-php5.6
  #   ports:
  #     - "8000:80"
  #   restart: always
  #   volumes: # persistance - tell Docker to keep these in tact. To replace with the entire wp-content directory
  #     - $WP/wp-content:/var/www/html/wp-content
  #     - $WP/wp-config.php:/var/www/html/wp-config.php
  #   networks:
  #     - back

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wp
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
    ports:
      - "3306:3306"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql

  # phpmyadmin:
  #   depends_on:
  #     - mysql
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   ports:
  #     - 8181:80
  #   environment:
  #     PMA_HOST: mysql
  #     MYSQL_ROOT_PASSWORD: wp #this must match you entered under 'mysql'
  #   networks:
  #     - back

volumes:
  db:

# networks:
#   back:

