version: '3.1'

services:

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    links:
      - wordpress
    depends_on:
      - wordpress
    ports:
      - "8080:80"
      # - "443:443"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
      - ${WP}:/var/www/html/:ro

  wordpress:
    build: .
    depends_on:
      - mysql
    restart: always
    env_file: .env
    volumes:
      - ${WP}/wp-content:/var/www/html/wp-content
      - ${WP}/wp-config.php:/var/www/html/wp-config.php
      - ./info.php:/var/www/html/info.php

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wp
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
    ports:
      - "3306:3306"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql

volumes:
  db:
